"""
Master skill definitions -- single source of truth for all recognized skills.
Each skill maps to exactly one of 15 consolidated types.
"""

SKILL_TYPES: list[str] = [
    "Programming Languages",
    "Frontend",
    "Backend",
    "Mobile",
    "Data & ML",
    "Databases",
    "Cloud Services",
    "DevOps & Infrastructure",
    "Security",
    "Testing & Quality",
    "Developer Tools",
    "Specialty",
    "Leadership & Management",
    "Interpersonal",
    "Problem Solving & Process",
]

SKILLS: dict[str, str] = {
    # ── Programming Languages ─────────────────────────────────────────────────
    "Python": "Programming Languages",
    "JavaScript": "Programming Languages",
    "TypeScript": "Programming Languages",
    "Java": "Programming Languages",
    "C++": "Programming Languages",
    "C#": "Programming Languages",
    "Go": "Programming Languages",
    "Golang": "Programming Languages",
    "Rust": "Programming Languages",
    "Ruby": "Programming Languages",
    "PHP": "Programming Languages",
    "Swift": "Programming Languages",
    "Kotlin": "Programming Languages",
    "Scala": "Programming Languages",
    "R": "Programming Languages",
    "MATLAB": "Programming Languages",
    "Perl": "Programming Languages",
    "Bash": "Programming Languages",
    "Shell": "Programming Languages",
    "PowerShell": "Programming Languages",
    "Lua": "Programming Languages",
    "Haskell": "Programming Languages",
    "Elixir": "Programming Languages",
    "Erlang": "Programming Languages",
    "Clojure": "Programming Languages",
    "F#": "Programming Languages",
    "OCaml": "Programming Languages",
    "Groovy": "Programming Languages",
    "Dart": "Programming Languages",
    "Julia": "Programming Languages",
    "Nim": "Programming Languages",
    "Zig": "Programming Languages",
    "Crystal": "Programming Languages",
    "Fortran": "Programming Languages",
    "COBOL": "Programming Languages",
    "Ada": "Programming Languages",
    "Assembly": "Programming Languages",
    "VHDL": "Programming Languages",
    "Verilog": "Programming Languages",
    "Prolog": "Programming Languages",
    "Lisp": "Programming Languages",
    "Scheme": "Programming Languages",
    "Racket": "Programming Languages",
    "Smalltalk": "Programming Languages",
    "Tcl": "Programming Languages",
    "Awk": "Programming Languages",
    "Solidity": "Programming Languages",
    "Vyper": "Programming Languages",
    "WebAssembly": "Programming Languages",
    "WASM": "Programming Languages",
    "SQL": "Programming Languages",
    "PL/SQL": "Programming Languages",
    "T-SQL": "Programming Languages",
    "HiveQL": "Programming Languages",
    "Apex": "Programming Languages",
    "ABAP": "Programming Languages",
    "VBA": "Programming Languages",
    "VBScript": "Programming Languages",
    "Objective-C": "Programming Languages",
    "CoffeeScript": "Programming Languages",
    "ReasonML": "Programming Languages",
    "PureScript": "Programming Languages",
    "Elm": "Programming Languages",
    "ClojureScript": "Programming Languages",
    "GDScript": "Programming Languages",
    "HLSL": "Programming Languages",
    "GLSL": "Programming Languages",
    "CUDA": "Programming Languages",
    "OpenCL": "Programming Languages",
    "MicroPython": "Programming Languages",
    "CircuitPython": "Programming Languages",
    "Arduino": "Programming Languages",
    "Processing": "Programming Languages",

    # ── Frontend ──────────────────────────────────────────────────────────────
    # Frontend Frameworks / Libraries
    "React": "Frontend",
    "React.js": "Frontend",
    "ReactJS": "Frontend",
    "Angular": "Frontend",
    "AngularJS": "Frontend",
    "Vue": "Frontend",
    "Vue.js": "Frontend",
    "VueJS": "Frontend",
    "Next.js": "Frontend",
    "NextJS": "Frontend",
    "Nuxt.js": "Frontend",
    "NuxtJS": "Frontend",
    "Svelte": "Frontend",
    "SvelteKit": "Frontend",
    "SolidJS": "Frontend",
    "Solid.js": "Frontend",
    "Qwik": "Frontend",
    "Astro": "Frontend",
    "Remix": "Frontend",
    "Gatsby": "Frontend",
    "Ember.js": "Frontend",
    "EmberJS": "Frontend",
    "Backbone.js": "Frontend",
    "BackboneJS": "Frontend",
    "Preact": "Frontend",
    "Lit": "Frontend",
    "Alpine.js": "Frontend",
    "AlpineJS": "Frontend",
    "HTMX": "Frontend",
    "Stimulus": "Frontend",
    "Turbo": "Frontend",
    "Hotwire": "Frontend",
    "Mithril": "Frontend",
    "Inferno": "Frontend",
    "Redux": "Frontend",
    "Redux Toolkit": "Frontend",
    "MobX": "Frontend",
    "Zustand": "Frontend",
    "Recoil": "Frontend",
    "Jotai": "Frontend",
    "XState": "Frontend",
    "React Query": "Frontend",
    "TanStack Query": "Frontend",
    "SWR": "Frontend",
    "Apollo Client": "Frontend",
    "Urql": "Frontend",
    "jQuery": "Frontend",
    "Prototype.js": "Frontend",
    # Frontend Styling
    "HTML": "Frontend",
    "HTML5": "Frontend",
    "CSS": "Frontend",
    "CSS3": "Frontend",
    "Sass": "Frontend",
    "SCSS": "Frontend",
    "Less": "Frontend",
    "Stylus": "Frontend",
    "Tailwind": "Frontend",
    "Tailwind CSS": "Frontend",
    "Bootstrap": "Frontend",
    "Foundation": "Frontend",
    "Bulma": "Frontend",
    "Material UI": "Frontend",
    "MUI": "Frontend",
    "Ant Design": "Frontend",
    "Chakra UI": "Frontend",
    "Mantine": "Frontend",
    "Shadcn/ui": "Frontend",
    "Radix UI": "Frontend",
    "Headless UI": "Frontend",
    "DaisyUI": "Frontend",
    "Semantic UI": "Frontend",
    "Vuetify": "Frontend",
    "PrimeVue": "Frontend",
    "Quasar": "Frontend",
    "Element Plus": "Frontend",
    "Naive UI": "Frontend",
    "Flowbite": "Frontend",
    "CSS Modules": "Frontend",
    "Styled Components": "Frontend",
    "Emotion": "Frontend",
    "Stitches": "Frontend",
    "Vanilla Extract": "Frontend",
    "Storybook": "Frontend",

    # ── Backend ───────────────────────────────────────────────────────────────
    # Backend Frameworks
    "FastAPI": "Backend",
    "Django": "Backend",
    "Django REST Framework": "Backend",
    "DRF": "Backend",
    "Flask": "Backend",
    "Litestar": "Backend",
    "Starlette": "Backend",
    "Tornado": "Backend",
    "Sanic": "Backend",
    "Falcon": "Backend",
    "Bottle": "Backend",
    "Pyramid": "Backend",
    "Express": "Backend",
    "Express.js": "Backend",
    "ExpressJS": "Backend",
    "NestJS": "Backend",
    "Nest.js": "Backend",
    "Fastify": "Backend",
    "Koa": "Backend",
    "Hapi": "Backend",
    "AdonisJS": "Backend",
    "Feathers.js": "Backend",
    "Loopback": "Backend",
    "Spring": "Backend",
    "Spring Boot": "Backend",
    "Spring MVC": "Backend",
    "Spring Security": "Backend",
    "Spring Cloud": "Backend",
    "Micronaut": "Backend",
    "Quarkus": "Backend",
    "Vert.x": "Backend",
    "Dropwizard": "Backend",
    "Play Framework": "Backend",
    "Rails": "Backend",
    "Ruby on Rails": "Backend",
    "Sinatra": "Backend",
    "Hanami": "Backend",
    "Laravel": "Backend",
    "Symfony": "Backend",
    "Lumen": "Backend",
    "CodeIgniter": "Backend",
    "CakePHP": "Backend",
    "Slim": "Backend",
    "Phalcon": "Backend",
    "ASP.NET": "Backend",
    "ASP.NET Core": "Backend",
    ".NET": "Backend",
    ".NET Core": "Backend",
    "Blazor": "Backend",
    "SignalR": "Backend",
    "Node.js": "Backend",
    "NodeJS": "Backend",
    "Deno": "Backend",
    "Bun": "Backend",
    "Gin": "Backend",
    "Echo": "Backend",
    "Fiber": "Backend",
    "Chi": "Backend",
    "Gorilla": "Backend",
    "Beego": "Backend",
    "Actix": "Backend",
    "Rocket": "Backend",
    "Axum": "Backend",
    "Warp": "Backend",
    "Tide": "Backend",
    "Phoenix": "Backend",
    "Plug": "Backend",
    "Absinthe": "Backend",
    "Ktor": "Backend",
    "Vapor": "Backend",
    # API Standards and Protocols
    "REST": "Backend",
    "RESTful": "Backend",
    "GraphQL": "Backend",
    "gRPC": "Backend",
    "WebSockets": "Backend",
    "WebSocket": "Backend",
    "SOAP": "Backend",
    "XML-RPC": "Backend",
    "JSON-RPC": "Backend",
    "Thrift": "Backend",
    "Avro": "Backend",
    "Protobuf": "Backend",
    "Protocol Buffers": "Backend",
    "OpenAPI": "Backend",
    "Swagger": "Backend",
    "AsyncAPI": "Backend",
    "RAML": "Backend",
    "OData": "Backend",
    "HAL": "Backend",
    "HATEOAS": "Backend",
    "tRPC": "Backend",
    "OAuth": "Backend",
    "OAuth2": "Backend",
    "OAuth 2.0": "Backend",
    "OpenID Connect": "Backend",
    "OIDC": "Backend",
    "JWT": "Backend",
    "SAML": "Backend",
    "LDAP": "Backend",
    "Active Directory": "Backend",
    "SSO": "Backend",
    "HTTP": "Backend",
    "HTTPS": "Backend",
    "HTTP/2": "Backend",
    "HTTP/3": "Backend",
    "QUIC": "Backend",
    "TCP/IP": "Backend",
    "UDP": "Backend",
    "DNS": "Backend",
    "TLS": "Backend",
    "SSL": "Backend",
    "mTLS": "Backend",
    "WebRTC": "Backend",
    "Server-Sent Events": "Backend",
    "SSE": "Backend",

    # ── Mobile ────────────────────────────────────────────────────────────────
    "iOS": "Mobile",
    "Android": "Mobile",
    "React Native": "Mobile",
    "Flutter": "Mobile",
    "Xamarin": "Mobile",
    "Ionic": "Mobile",
    "Capacitor": "Mobile",
    "Cordova": "Mobile",
    "PhoneGap": "Mobile",
    "NativeScript": "Mobile",
    "Expo": "Mobile",
    "SwiftUI": "Mobile",
    "UIKit": "Mobile",
    "AppKit": "Mobile",
    "Jetpack Compose": "Mobile",
    "Android SDK": "Mobile",
    "Kotlin Multiplatform": "Mobile",
    "KMM": "Mobile",
    "MAUI": "Mobile",
    ".NET MAUI": "Mobile",
    "Xcode": "Mobile",
    "Android Studio": "Mobile",

    # ── Data & ML ─────────────────────────────────────────────────────────────
    # Data Science / Analytics
    "NumPy": "Data & ML",
    "Pandas": "Data & ML",
    "Polars": "Data & ML",
    "Dask": "Data & ML",
    "Vaex": "Data & ML",
    "Matplotlib": "Data & ML",
    "Seaborn": "Data & ML",
    "Plotly": "Data & ML",
    "Bokeh": "Data & ML",
    "Altair": "Data & ML",
    "Dash": "Data & ML",
    "Jupyter": "Data & ML",
    "JupyterLab": "Data & ML",
    "Jupyter Notebook": "Data & ML",
    "IPython": "Data & ML",
    "SciPy": "Data & ML",
    "Statsmodels": "Data & ML",
    "SQLAlchemy": "Data & ML",
    "Alembic": "Data & ML",
    "Peewee": "Data & ML",
    "Tortoise ORM": "Data & ML",
    # Machine Learning / AI
    "TensorFlow": "Data & ML",
    "PyTorch": "Data & ML",
    "Keras": "Data & ML",
    "JAX": "Data & ML",
    "Flax": "Data & ML",
    "Scikit-learn": "Data & ML",
    "sklearn": "Data & ML",
    "XGBoost": "Data & ML",
    "LightGBM": "Data & ML",
    "CatBoost": "Data & ML",
    "Hugging Face": "Data & ML",
    "Transformers": "Data & ML",
    "Diffusers": "Data & ML",
    "PEFT": "Data & ML",
    "LangChain": "Data & ML",
    "LlamaIndex": "Data & ML",
    "Haystack": "Data & ML",
    "Semantic Kernel": "Data & ML",
    "spaCy": "Data & ML",
    "NLTK": "Data & ML",
    "Gensim": "Data & ML",
    "TextBlob": "Data & ML",
    "FastText": "Data & ML",
    "OpenCV": "Data & ML",
    "PIL": "Data & ML",
    "Pillow": "Data & ML",
    "torchvision": "Data & ML",
    "Detectron2": "Data & ML",
    "YOLO": "Data & ML",
    "MLflow": "Data & ML",
    "Weights & Biases": "Data & ML",
    "W&B": "Data & ML",
    "Neptune": "Data & ML",
    "Kubeflow": "Data & ML",
    "Metaflow": "Data & ML",
    "ZenML": "Data & ML",
    "Kedro": "Data & ML",
    "DVC": "Data & ML",
    "ONNX": "Data & ML",
    "TensorRT": "Data & ML",
    "TorchServe": "Data & ML",
    "BentoML": "Data & ML",
    "Seldon": "Data & ML",
    "Ray": "Data & ML",
    "Ray Tune": "Data & ML",
    "Ray Serve": "Data & ML",
    "Optuna": "Data & ML",
    "Hyperopt": "Data & ML",
    "FAISS": "Data & ML",
    "Annoy": "Data & ML",
    "LLM": "Data & ML",
    "RAG": "Data & ML",
    "fine-tuning": "Data & ML",
    "prompt engineering": "Data & ML",
    "reinforcement learning": "Data & ML",
    "computer vision": "Data & ML",
    "NLP": "Data & ML",
    "natural language processing": "Data & ML",
    "machine learning": "Data & ML",
    "deep learning": "Data & ML",
    # Data Engineering
    "Apache Spark": "Data & ML",
    "PySpark": "Data & ML",
    "Hadoop": "Data & ML",
    "MapReduce": "Data & ML",
    "HDFS": "Data & ML",
    "Apache Flink": "Data & ML",
    "Flink": "Data & ML",
    "Apache Beam": "Data & ML",
    "Beam": "Data & ML",
    "Apache Hive": "Data & ML",
    "Hive": "Data & ML",
    "Presto": "Data & ML",
    "Trino": "Data & ML",
    "Apache Druid": "Data & ML",
    "Apache Iceberg": "Data & ML",
    "Delta Lake": "Data & ML",
    "Apache Hudi": "Data & ML",
    "dbt": "Data & ML",
    "Apache Airflow": "Data & ML",
    "Airflow": "Data & ML",
    "Prefect": "Data & ML",
    "Dagster": "Data & ML",
    "Luigi": "Data & ML",
    "Apache NiFi": "Data & ML",
    "Talend": "Data & ML",
    "Informatica": "Data & ML",
    "Fivetran": "Data & ML",
    "Airbyte": "Data & ML",
    "Stitch": "Data & ML",
    # Analytics / BI (from TECHNOLOGIES_LIST)
    "Tableau": "Data & ML",
    "Power BI": "Data & ML",
    "Looker": "Data & ML",
    "Metabase": "Data & ML",
    "Redash": "Data & ML",
    "Apache Superset": "Data & ML",
    "Mode Analytics": "Data & ML",
    "Hex": "Data & ML",
    "Google Analytics": "Data & ML",
    "Mixpanel": "Data & ML",
    "Amplitude": "Data & ML",
    "Segment": "Data & ML",
    "Heap": "Data & ML",
    "FullStory": "Data & ML",
    "Hotjar": "Data & ML",
    "Pendo": "Data & ML",
    # AI / ML Platforms (from TECHNOLOGIES_LIST)
    "OpenAI API": "Data & ML",
    "Anthropic": "Data & ML",
    "Cohere": "Data & ML",
    "Ollama": "Data & ML",
    "Hugging Face Hub": "Data & ML",
    "Replicate": "Data & ML",
    "AWS SageMaker": "Data & ML",
    "Azure Machine Learning": "Data & ML",
    "Vertex AI": "Data & ML",
    "Pinecone": "Data & ML",
    "Weaviate": "Data & ML",
    "Qdrant": "Data & ML",
    "Chroma": "Data & ML",
    # Data Pipeline / ETL / ELT (from TECHNOLOGIES_LIST, non-duplicates)
    "dbt Cloud": "Data & ML",
    "dbt Core": "Data & ML",
    "Mage": "Data & ML",
    "Azure Data Factory": "Data & ML",
    "AWS Glue": "Data & ML",
    "Google Dataflow": "Data & ML",
    "Kafka Streams": "Data & ML",
    "ksqlDB": "Data & ML",
    "Firebase Analytics": "Data & ML",
    "Looker Studio": "Data & ML",

    # ── Databases ─────────────────────────────────────────────────────────────
    # Databases -- Concepts
    "NoSQL": "Databases",
    "NewSQL": "Databases",
    "ACID": "Databases",
    "Database design": "Databases",
    "Schema design": "Databases",
    "Normalization": "Databases",
    "Indexing": "Databases",
    "Query optimization": "Databases",
    "Stored procedures": "Databases",
    "Transactions": "Databases",
    "Replication": "Databases",
    "Sharding": "Databases",
    "ORM": "Databases",
    "ActiveRecord": "Databases",
    "Sequelize": "Databases",
    "TypeORM": "Databases",
    "Prisma": "Databases",
    "Drizzle": "Databases",
    "Mongoose": "Databases",
    "Full-text search": "Databases",
    "Vector search": "Databases",
    # Relational Databases (from TECHNOLOGIES_LIST)
    "PostgreSQL": "Databases",
    "Postgres": "Databases",
    "MySQL": "Databases",
    "MariaDB": "Databases",
    "SQLite": "Databases",
    "Oracle": "Databases",
    "Oracle Database": "Databases",
    "MS SQL Server": "Databases",
    "SQL Server": "Databases",
    "Microsoft SQL Server": "Databases",
    "IBM Db2": "Databases",
    "SAP HANA": "Databases",
    "Teradata": "Databases",
    "CockroachDB": "Databases",
    "YugabyteDB": "Databases",
    "SingleStore": "Databases",
    "PlanetScale": "Databases",
    "Neon": "Databases",
    "Supabase": "Databases",
    "TimescaleDB": "Databases",
    # NoSQL Databases (from TECHNOLOGIES_LIST)
    "MongoDB": "Databases",
    "CouchDB": "Databases",
    "Couchbase": "Databases",
    "ArangoDB": "Databases",
    "Cassandra": "Databases",
    "Apache Cassandra": "Databases",
    "ScyllaDB": "Databases",
    "HBase": "Databases",
    "Redis": "Databases",
    "KeyDB": "Databases",
    "Dragonfly": "Databases",
    "DynamoDB": "Databases",
    "FaunaDB": "Databases",
    "Elasticsearch": "Databases",
    "OpenSearch": "Databases",
    "Solr": "Databases",
    "MeiliSearch": "Databases",
    "Typesense": "Databases",
    "Algolia": "Databases",
    "Neo4j": "Databases",
    "Amazon Neptune": "Databases",
    "InfluxDB": "Databases",
    "VictoriaMetrics": "Databases",
    "Firebase Realtime Database": "Databases",
    "Firestore": "Databases",
    "LevelDB": "Databases",
    "RocksDB": "Databases",
    # Data Warehouses / OLAP (from TECHNOLOGIES_LIST)
    "Snowflake": "Databases",
    "BigQuery": "Databases",
    "Redshift": "Databases",
    "Azure Synapse": "Databases",
    "Databricks": "Databases",
    "ClickHouse": "Databases",
    "Druid": "Databases",
    "Pinot": "Databases",
    "Greenplum": "Databases",
    "Vertica": "Databases",
    "DuckDB": "Databases",
    "Starburst": "Databases",

    # ── Cloud Services ────────────────────────────────────────────────────────
    # Cloud Providers
    "AWS": "Cloud Services",
    "Amazon Web Services": "Cloud Services",
    "Azure": "Cloud Services",
    "Microsoft Azure": "Cloud Services",
    "GCP": "Cloud Services",
    "Google Cloud": "Cloud Services",
    "Google Cloud Platform": "Cloud Services",
    "Oracle Cloud": "Cloud Services",
    "OCI": "Cloud Services",
    "IBM Cloud": "Cloud Services",
    "Alibaba Cloud": "Cloud Services",
    "Cloudflare": "Cloud Services",
    "Vercel": "Cloud Services",
    "Netlify": "Cloud Services",
    "Render": "Cloud Services",
    "Railway": "Cloud Services",
    "Fly.io": "Cloud Services",
    "Heroku": "Cloud Services",
    "DigitalOcean": "Cloud Services",
    "Linode": "Cloud Services",
    "Akamai": "Cloud Services",
    "Vultr": "Cloud Services",
    "Hetzner": "Cloud Services",
    # AWS Services
    "EC2": "Cloud Services",
    "ECS": "Cloud Services",
    "EKS": "Cloud Services",
    "Fargate": "Cloud Services",
    "Lambda": "Cloud Services",
    "App Runner": "Cloud Services",
    "Elastic Beanstalk": "Cloud Services",
    "LightSail": "Cloud Services",
    "S3": "Cloud Services",
    "S3 Glacier": "Cloud Services",
    "EFS": "Cloud Services",
    "FSx": "Cloud Services",
    "RDS": "Cloud Services",
    "Aurora": "Cloud Services",
    "ElastiCache": "Cloud Services",
    "DocumentDB": "Cloud Services",
    "Timestream": "Cloud Services",
    "QLDB": "Cloud Services",
    "MemoryDB": "Cloud Services",
    "EMR": "Cloud Services",
    "Glue": "Cloud Services",
    "Athena": "Cloud Services",
    "Lake Formation": "Cloud Services",
    "Kinesis": "Cloud Services",
    "SQS": "Cloud Services",
    "SNS": "Cloud Services",
    "EventBridge": "Cloud Services",
    "MQ": "Cloud Services",
    "CloudFront": "Cloud Services",
    "Route 53": "Cloud Services",
    "VPC": "Cloud Services",
    "Direct Connect": "Cloud Services",
    "Transit Gateway": "Cloud Services",
    "ALB": "Cloud Services",
    "NLB": "Cloud Services",
    "API Gateway": "Cloud Services",
    "App Mesh": "Cloud Services",
    "IAM": "Cloud Services",
    "Cognito": "Cloud Services",
    "Secrets Manager": "Cloud Services",
    "KMS": "Cloud Services",
    "WAF": "Cloud Services",
    "Shield": "Cloud Services",
    "GuardDuty": "Cloud Services",
    "Inspector": "Cloud Services",
    "Macie": "Cloud Services",
    "Security Hub": "Cloud Services",
    "CloudWatch": "Cloud Services",
    "CloudTrail": "Cloud Services",
    "X-Ray": "Cloud Services",
    "Config": "Cloud Services",
    "Trusted Advisor": "Cloud Services",
    "CodeCommit": "Cloud Services",
    "CodeBuild": "Cloud Services",
    "CodeDeploy": "Cloud Services",
    "CodePipeline": "Cloud Services",
    "CodeArtifact": "Cloud Services",
    "CloudFormation": "Cloud Services",
    "CDK": "Cloud Services",
    "SAM": "Cloud Services",
    "Amplify": "Cloud Services",
    "AppSync": "Cloud Services",
    "SageMaker": "Cloud Services",
    "Bedrock": "Cloud Services",
    "Rekognition": "Cloud Services",
    "Textract": "Cloud Services",
    "Comprehend": "Cloud Services",
    "Translate": "Cloud Services",
    "Transcribe": "Cloud Services",
    "Polly": "Cloud Services",
    "Lex": "Cloud Services",
    "Batch": "Cloud Services",
    "Step Functions": "Cloud Services",
    "ECR": "Cloud Services",
    "Elastic Container Registry": "Cloud Services",
    "OpenSearch Service": "Cloud Services",
    "MSK": "Cloud Services",
    "Managed Kafka": "Cloud Services",
    "CloudHSM": "Cloud Services",
    "ACM": "Cloud Services",
    "Systems Manager": "Cloud Services",
    "SSM": "Cloud Services",
    "Parameter Store": "Cloud Services",
    "Cost Explorer": "Cloud Services",
    "Budgets": "Cloud Services",
    "Organizations": "Cloud Services",
    "Control Tower": "Cloud Services",
    "Global Accelerator": "Cloud Services",
    "DataSync": "Cloud Services",
    "IoT Core": "Cloud Services",
    "IoT Greengrass": "Cloud Services",
    "AWS Transfer Family": "Cloud Services",
    "AWS DMS": "Cloud Services",
    "Database Migration Service": "Cloud Services",
    "AWS SCT": "Cloud Services",
    "Schema Conversion Tool": "Cloud Services",
    "AWS MGN": "Cloud Services",
    "Application Migration Service": "Cloud Services",
    "AWS Migration Hub": "Cloud Services",
    "AWS Snow Family": "Cloud Services",
    "Snowball": "Cloud Services",
    "Snowball Edge": "Cloud Services",
    "Snowcone": "Cloud Services",
    "Snowmobile": "Cloud Services",
    "AWS Outposts": "Cloud Services",
    "AWS Local Zones": "Cloud Services",
    "Amazon Connect": "Cloud Services",
    "Amazon Chime": "Cloud Services",
    "Amazon Pinpoint": "Cloud Services",
    "Amazon SES": "Cloud Services",
    "AWS Firewall Manager": "Cloud Services",
    "AWS Network Firewall": "Cloud Services",
    "AWS Audit Manager": "Cloud Services",
    "AWS Artifact": "Cloud Services",
    "AWS Compute Optimizer": "Cloud Services",
    "AWS Health": "Cloud Services",
    "Amazon Forecast": "Cloud Services",
    "Amazon Fraud Detector": "Cloud Services",
    "Amazon DevOps Guru": "Cloud Services",
    "Amazon CodeGuru": "Cloud Services",
    "Amazon Lookout for Metrics": "Cloud Services",
    "AWS Amplify Studio": "Cloud Services",
    "AWS Device Farm": "Cloud Services",
    "Amazon Location Service": "Cloud Services",
    "AWS Elemental": "Cloud Services",
    "AWS MediaConvert": "Cloud Services",
    "AWS MediaLive": "Cloud Services",
    "AWS MediaPackage": "Cloud Services",
    "Amazon IVS": "Cloud Services",
    "Amazon Honeycode": "Cloud Services",
    "Amazon Managed Blockchain": "Cloud Services",
    "AWS Nitro": "Cloud Services",
    "AWS Nitro System": "Cloud Services",
    "AWS Nitro Enclaves": "Cloud Services",
    "EC2 Image Builder": "Cloud Services",
    "AWS Systems Manager Patch Manager": "Cloud Services",
    "AWS Backup": "Cloud Services",
    "AWS Disaster Recovery": "Cloud Services",
    "AWS Resilience Hub": "Cloud Services",
    "AWS Well-Architected Tool": "Cloud Services",
    "AWS Proton": "Cloud Services",
    "AWS App2Container": "Cloud Services",
    "Amazon EKS Anywhere": "Cloud Services",
    "Amazon ECS Anywhere": "Cloud Services",
    "AWS Wavelength": "Cloud Services",
    "AWS Ground Station": "Cloud Services",
    "Amazon Braket": "Cloud Services",
    "Amazon Managed Grafana": "Cloud Services",
    "Amazon Managed Prometheus": "Cloud Services",
    "AWS Clean Rooms": "Cloud Services",
    "Amazon DataZone": "Cloud Services",
    "AWS Glue DataBrew": "Cloud Services",
    "AWS Entity Resolution": "Cloud Services",
    "Amazon SageMaker Studio": "Cloud Services",
    "Amazon SageMaker Canvas": "Cloud Services",
    "Amazon SageMaker Clarify": "Cloud Services",
    "Amazon SageMaker Feature Store": "Cloud Services",
    "Amazon SageMaker Pipelines": "Cloud Services",
    "Amazon SageMaker Model Registry": "Cloud Services",
    "Amazon Bedrock": "Cloud Services",
    "Amazon Titan": "Cloud Services",
    "Amazon Nova": "Cloud Services",
    "Amazon Q": "Cloud Services",
    "Amazon Q Developer": "Cloud Services",
    "Amazon Q Business": "Cloud Services",
    "AWS CodeWhisperer": "Cloud Services",
    "VPC Lattice": "Cloud Services",
    "AWS PrivateLink": "Cloud Services",
    "Amazon VPC": "Cloud Services",
    "VPC Flow Logs": "Cloud Services",
    "AWS Transit Gateway": "Cloud Services",
    "AWS Cloud WAN": "Cloud Services",
    "AWS Resource Access Manager": "Cloud Services",
    "AWS RAM": "Cloud Services",
    "AWS Service Quotas": "Cloud Services",
    "AWS Launch Wizard": "Cloud Services",
    "AWS Marketplace": "Cloud Services",
    "Amazon WorkSpaces": "Cloud Services",
    "Amazon AppStream": "Cloud Services",
    "AWS End User Computing": "Cloud Services",
    # Azure Services
    "Azure Virtual Machines": "Cloud Services",
    "Azure VM": "Cloud Services",
    "AKS": "Cloud Services",
    "Azure Container Instances": "Cloud Services",
    "Azure Functions": "Cloud Services",
    "Azure App Service": "Cloud Services",
    "Azure Container Apps": "Cloud Services",
    "Azure Static Web Apps": "Cloud Services",
    "Azure Kubernetes Service": "Cloud Services",
    "Azure Blob Storage": "Cloud Services",
    "Azure Data Lake": "Cloud Services",
    "Azure Files": "Cloud Services",
    "Azure SQL": "Cloud Services",
    "Azure SQL Database": "Cloud Services",
    "Azure Cosmos DB": "Cloud Services",
    "Azure Database for PostgreSQL": "Cloud Services",
    "Azure Database for MySQL": "Cloud Services",
    "Azure Cache for Redis": "Cloud Services",
    "Azure Synapse Analytics": "Cloud Services",
    "Azure Stream Analytics": "Cloud Services",
    "Azure Event Hubs": "Cloud Services",
    "Azure Service Bus": "Cloud Services",
    "Azure Event Grid": "Cloud Services",
    "Azure CDN": "Cloud Services",
    "Azure Front Door": "Cloud Services",
    "Azure DNS": "Cloud Services",
    "Azure Load Balancer": "Cloud Services",
    "Azure VNet": "Cloud Services",
    "Azure ExpressRoute": "Cloud Services",
    "Azure Application Gateway": "Cloud Services",
    "Azure API Management": "Cloud Services",
    "Azure Active Directory": "Cloud Services",
    "Azure AD": "Cloud Services",
    "Entra ID": "Cloud Services",
    "Azure Key Vault": "Cloud Services",
    "Azure Defender": "Cloud Services",
    "Azure Sentinel": "Cloud Services",
    "Azure Monitor": "Cloud Services",
    "Azure Log Analytics": "Cloud Services",
    "Azure Application Insights": "Cloud Services",
    "Azure DevOps": "Cloud Services",
    "Azure Repos": "Cloud Services",
    "Azure Pipelines": "Cloud Services",
    "Azure Artifacts": "Cloud Services",
    "ARM Templates": "Cloud Services",
    "Bicep": "Cloud Services",
    "Azure Batch": "Cloud Services",
    "Azure Logic Apps": "Cloud Services",
    "Azure Container Registry": "Cloud Services",
    "ACR": "Cloud Services",
    "Azure Notification Hubs": "Cloud Services",
    "Azure SignalR": "Cloud Services",
    "Power Platform": "Cloud Services",
    "Power Apps": "Cloud Services",
    "Power Automate": "Cloud Services",
    # GCP Services
    "GKE": "Cloud Services",
    "Google Kubernetes Engine": "Cloud Services",
    "Cloud Run": "Cloud Services",
    "Cloud Functions": "Cloud Services",
    "Compute Engine": "Cloud Services",
    "App Engine": "Cloud Services",
    "Cloud Build": "Cloud Services",
    "Cloud Storage": "Cloud Services",
    "Cloud SQL": "Cloud Services",
    "Firebase": "Cloud Services",
    "Cloud Spanner": "Cloud Services",
    "Cloud Bigtable": "Cloud Services",
    "AlloyDB": "Cloud Services",
    "Memorystore": "Cloud Services",
    "Dataflow": "Cloud Services",
    "Dataproc": "Cloud Services",
    "Pub/Sub": "Cloud Services",
    "Datastream": "Cloud Services",
    "Cloud CDN": "Cloud Services",
    "Cloud DNS": "Cloud Services",
    "Cloud Load Balancing": "Cloud Services",
    "Cloud Armor": "Cloud Services",
    "Identity Platform": "Cloud Services",
    "Firebase Auth": "Cloud Services",
    "Secret Manager": "Cloud Services",
    "Cloud KMS": "Cloud Services",
    "Cloud Monitoring": "Cloud Services",
    "Cloud Logging": "Cloud Services",
    "Cloud Trace": "Cloud Services",
    "Cloud Source Repositories": "Cloud Services",
    "Cloud Deploy": "Cloud Services",
    "Artifact Registry": "Cloud Services",
    "AutoML": "Cloud Services",
    "Vision AI": "Cloud Services",
    "Speech-to-Text": "Cloud Services",
    "Text-to-Speech": "Cloud Services",
    "Dialogflow": "Cloud Services",
    "Cloud Composer": "Cloud Services",
    "Workflows": "Cloud Services",
    "Eventarc": "Cloud Services",
    # Cloud Architecture -- Strategies & Patterns (from SKILLS_LIST)
    "Well-Architected Framework": "Cloud Services",
    "AWS Well-Architected Framework": "Cloud Services",
    "Well-Architected Review": "Cloud Services",
    "Operational Excellence": "Cloud Services",
    "Security pillar": "Cloud Services",
    "Reliability pillar": "Cloud Services",
    "Performance Efficiency": "Cloud Services",
    "Cost Optimization pillar": "Cloud Services",
    "Sustainability pillar": "Cloud Services",
    "Cloud migration": "Cloud Services",
    "Cloud adoption": "Cloud Services",
    "Cloud transformation": "Cloud Services",
    "AWS Cloud Adoption Framework": "Cloud Services",
    "AWS CAF": "Cloud Services",
    "lift and shift": "Cloud Services",
    "rehost": "Cloud Services",
    "replatform": "Cloud Services",
    "repurchase": "Cloud Services",
    "refactor": "Cloud Services",
    "re-architect": "Cloud Services",
    "retire": "Cloud Services",
    "retain": "Cloud Services",
    "migration strategy": "Cloud Services",
    "cloud readiness assessment": "Cloud Services",
    "migration factory": "Cloud Services",
    "Landing Zone": "Cloud Services",
    "AWS Landing Zone": "Cloud Services",
    "AWS Control Tower": "Cloud Services",
    "multi-account strategy": "Cloud Services",
    "Service Control Policies": "Cloud Services",
    "SCP": "Cloud Services",
    "permission boundaries": "Cloud Services",
    "AWS Organizations": "Cloud Services",
    "organizational units": "Cloud Services",
    "OU": "Cloud Services",
    "account vending machine": "Cloud Services",
    "guardrails": "Cloud Services",
    "Cloud Center of Excellence": "Cloud Services",
    "CCoE": "Cloud Services",
    "High availability": "Cloud Services",
    "HA": "Cloud Services",
    "Fault tolerance": "Cloud Services",
    "Disaster recovery": "Cloud Services",
    "DR": "Cloud Services",
    "RTO": "Cloud Services",
    "RPO": "Cloud Services",
    "business continuity": "Cloud Services",
    "BCP": "Cloud Services",
    "multi-region": "Cloud Services",
    "multi-AZ": "Cloud Services",
    "Availability Zone": "Cloud Services",
    "AZ": "Cloud Services",
    "active-active": "Cloud Services",
    "active-passive": "Cloud Services",
    "warm standby": "Cloud Services",
    "pilot light": "Cloud Services",
    "hot standby": "Cloud Services",
    "cold standby": "Cloud Services",
    "failover": "Cloud Services",
    "failback": "Cloud Services",
    "regional failover": "Cloud Services",
    "chaos engineering": "Cloud Services",
    "fault injection": "Cloud Services",
    "GameDay": "Cloud Services",
    "resilience testing": "Cloud Services",
    "recovery testing": "Cloud Services",
    "Scalability": "Cloud Services",
    "horizontal scaling": "Cloud Services",
    "vertical scaling": "Cloud Services",
    "Auto-scaling": "Cloud Services",
    "Auto Scaling Group": "Cloud Services",
    "ASG": "Cloud Services",
    "target tracking": "Cloud Services",
    "step scaling": "Cloud Services",
    "scheduled scaling": "Cloud Services",
    "predictive scaling": "Cloud Services",
    "load balancing": "Cloud Services",
    "Application Load Balancer": "Cloud Services",
    "Network Load Balancer": "Cloud Services",
    "latency-based routing": "Cloud Services",
    "CDN": "Cloud Services",
    "content delivery": "Cloud Services",
    "Edge computing": "Cloud Services",
    "edge location": "Cloud Services",
    "caching strategy": "Cloud Services",
    "cache invalidation": "Cloud Services",
    "TTL": "Cloud Services",
    "Virtual Private Cloud": "Cloud Services",
    "VPC design": "Cloud Services",
    "subnet design": "Cloud Services",
    "public subnet": "Cloud Services",
    "private subnet": "Cloud Services",
    "CIDR": "Cloud Services",
    "IP addressing": "Cloud Services",
    "NAT Gateway": "Cloud Services",
    "NAT instance": "Cloud Services",
    "Internet Gateway": "Cloud Services",
    "egress-only gateway": "Cloud Services",
    "VPC Peering": "Cloud Services",
    "VPC peering": "Cloud Services",
    "transit routing": "Cloud Services",
    "VPC endpoint": "Cloud Services",
    "interface endpoint": "Cloud Services",
    "gateway endpoint": "Cloud Services",
    "AWS Direct Connect": "Cloud Services",
    "VPN": "Cloud Services",
    "Site-to-Site VPN": "Cloud Services",
    "Client VPN": "Cloud Services",
    "AWS VPN": "Cloud Services",
    "CloudWAN": "Cloud Services",
    "network segmentation": "Cloud Services",
    "security groups": "Cloud Services",
    "NACLs": "Cloud Services",
    "network ACL": "Cloud Services",
    "DNS failover": "Cloud Services",
    "health checks": "Cloud Services",
    "latency routing": "Cloud Services",
    "geolocation routing": "Cloud Services",
    "weighted routing": "Cloud Services",
    "traffic policies": "Cloud Services",
    "Zero Trust architecture": "Cloud Services",
    "ZTNA": "Cloud Services",
    "defense in depth": "Cloud Services",
    "shared responsibility model": "Cloud Services",
    "least privilege": "Cloud Services",
    "principle of least privilege": "Cloud Services",
    "identity-based policies": "Cloud Services",
    "resource-based policies": "Cloud Services",
    "cross-account access": "Cloud Services",
    "cross-account roles": "Cloud Services",
    "assume role": "Cloud Services",
    "federated access": "Cloud Services",
    "federation": "Cloud Services",
    "identity federation": "Cloud Services",
    "service-linked roles": "Cloud Services",
    "instance profiles": "Cloud Services",
    "IAM roles": "Cloud Services",
    "tag-based access control": "Cloud Services",
    "attribute-based access control": "Cloud Services",
    "encryption at rest": "Cloud Services",
    "encryption in transit": "Cloud Services",
    "envelope encryption": "Cloud Services",
    "key management": "Cloud Services",
    "customer-managed keys": "Cloud Services",
    "CMK": "Cloud Services",
    "data classification": "Cloud Services",
    "data sovereignty": "Cloud Services",
    "data residency": "Cloud Services",
    "compliance automation": "Cloud Services",
    "audit logging": "Cloud Services",
    "immutable logs": "Cloud Services",
    "AWS Shield": "Cloud Services",
    "DDoS protection": "Cloud Services",
    "bot protection": "Cloud Services",
    "FinOps": "Cloud Services",
    "cost optimization": "Cloud Services",
    "cloud cost management": "Cloud Services",
    "Reserved Instances": "Cloud Services",
    "RI": "Cloud Services",
    "Savings Plans": "Cloud Services",
    "Compute Savings Plans": "Cloud Services",
    "EC2 Instance Savings Plans": "Cloud Services",
    "Spot Instances": "Cloud Services",
    "Spot Fleet": "Cloud Services",
    "On-Demand": "Cloud Services",
    "right-sizing": "Cloud Services",
    "resource tagging": "Cloud Services",
    "cost allocation tags": "Cloud Services",
    "cost allocation": "Cloud Services",
    "showback": "Cloud Services",
    "chargeback": "Cloud Services",
    "AWS Cost Explorer": "Cloud Services",
    "AWS Budgets": "Cloud Services",
    "AWS Pricing Calculator": "Cloud Services",
    "Compute Optimizer": "Cloud Services",
    "serverless architecture": "Cloud Services",
    "FaaS": "Cloud Services",
    "event-driven architecture": "Cloud Services",
    "event-driven": "Cloud Services",
    "AWS Lambda": "Cloud Services",
    "Lambda@Edge": "Cloud Services",
    "Lambda layers": "Cloud Services",
    "state machine": "Cloud Services",
    "workflow orchestration": "Cloud Services",
    "event bus": "Cloud Services",
    "event schema": "Cloud Services",
    "event sourcing": "Cloud Services",
    "fan-out pattern": "Cloud Services",
    "pub/sub pattern": "Cloud Services",
    "dead letter queue": "Cloud Services",
    "DLQ": "Cloud Services",
    "FIFO queue": "Cloud Services",
    "message deduplication": "Cloud Services",
    "idempotency": "Cloud Services",
    "at-least-once delivery": "Cloud Services",
    "exactly-once delivery": "Cloud Services",
    "AWS Fargate": "Cloud Services",
    "container orchestration": "Cloud Services",
    "container registry": "Cloud Services",
    "image scanning": "Cloud Services",
    "service mesh": "Cloud Services",
    "sidecar proxy": "Cloud Services",
    "blue-green deployment": "Cloud Services",
    "canary deployment": "Cloud Services",
    "rolling deployment": "Cloud Services",
    "infrastructure as code": "Cloud Services",
    "immutable infrastructure": "Cloud Services",
    "ArgoCD": "Cloud Services",
    "Flux": "Cloud Services",
    "data lake": "Cloud Services",
    "data lakehouse": "Cloud Services",
    "data mesh": "Cloud Services",
    "data warehouse": "Cloud Services",
    "S3 data lake": "Cloud Services",
    "AWS Glue": "Cloud Services",
    "Glue Catalog": "Cloud Services",
    "serverless query": "Cloud Services",
    "Redshift Spectrum": "Cloud Services",
    "Kinesis Data Streams": "Cloud Services",
    "Kinesis Data Firehose": "Cloud Services",
    "Kinesis Data Analytics": "Cloud Services",
    "streaming architecture": "Cloud Services",
    "lambda architecture": "Cloud Services",
    "kappa architecture": "Cloud Services",
    "CDC": "Cloud Services",
    "change data capture": "Cloud Services",
    "data replication": "Cloud Services",
    "ETL": "Cloud Services",
    "ELT": "Cloud Services",
    "data pipeline": "Cloud Services",
    "data integration": "Cloud Services",
    "data governance": "Cloud Services",
    "data catalog": "Cloud Services",
    "data lineage": "Cloud Services",
    "object storage": "Cloud Services",
    "S3 Intelligent-Tiering": "Cloud Services",
    "S3 Standard-IA": "Cloud Services",
    "S3 One Zone-IA": "Cloud Services",
    "S3 Glacier Deep Archive": "Cloud Services",
    "S3 lifecycle policy": "Cloud Services",
    "storage tiering": "Cloud Services",
    "data archival": "Cloud Services",
    "EBS": "Cloud Services",
    "block storage": "Cloud Services",
    "file storage": "Cloud Services",
    "shared file system": "Cloud Services",
    "NFS": "Cloud Services",
    "SMB": "Cloud Services",
    "Multi-cloud": "Cloud Services",
    "Hybrid cloud": "Cloud Services",
    "Cloud-native": "Cloud Services",
    "cloud first": "Cloud Services",
    "microservices": "Cloud Services",
    "API-first": "Cloud Services",
    "API gateway pattern": "Cloud Services",
    "strangler fig pattern": "Cloud Services",
    "bulkhead pattern": "Cloud Services",
    "circuit breaker": "Cloud Services",
    "retry with backoff": "Cloud Services",
    "rate limiting": "Cloud Services",
    "throttling": "Cloud Services",
    "observability": "Cloud Services",
    "distributed tracing": "Cloud Services",
    "SLO": "Cloud Services",
    "SLA": "Cloud Services",
    "SLI": "Cloud Services",
    "error budget": "Cloud Services",
    "toil reduction": "Cloud Services",
    "runbook": "Cloud Services",
    "playbook": "Cloud Services",
    "runbook automation": "Cloud Services",

    # ── DevOps & Infrastructure ───────────────────────────────────────────────
    # DevOps / Development Practices (from SKILLS_LIST)
    "CI/CD": "DevOps & Infrastructure",
    "Continuous Integration": "DevOps & Infrastructure",
    "Continuous Deployment": "DevOps & Infrastructure",
    "Continuous Delivery": "DevOps & Infrastructure",
    "DevOps": "DevOps & Infrastructure",
    "DevSecOps": "DevOps & Infrastructure",
    "GitOps": "DevOps & Infrastructure",
    "MLOps": "DevOps & Infrastructure",
    "SRE": "DevOps & Infrastructure",
    "Site Reliability Engineering": "DevOps & Infrastructure",
    "Agile": "DevOps & Infrastructure",
    "Scrum": "DevOps & Infrastructure",
    "Kanban": "DevOps & Infrastructure",
    "SAFe": "DevOps & Infrastructure",
    "XP": "DevOps & Infrastructure",
    "Extreme Programming": "DevOps & Infrastructure",
    "Lean": "DevOps & Infrastructure",
    "Waterfall": "DevOps & Infrastructure",
    "Pair programming": "DevOps & Infrastructure",
    "Code review": "DevOps & Infrastructure",
    "Domain-Driven Design": "DevOps & Infrastructure",
    "DDD": "DevOps & Infrastructure",
    "Event-Driven Architecture": "DevOps & Infrastructure",
    "Event Sourcing": "DevOps & Infrastructure",
    "CQRS": "DevOps & Infrastructure",
    "Hexagonal Architecture": "DevOps & Infrastructure",
    "Clean Architecture": "DevOps & Infrastructure",
    "Microservices": "DevOps & Infrastructure",
    "Monolith": "DevOps & Infrastructure",
    "SOA": "DevOps & Infrastructure",
    "Serverless": "DevOps & Infrastructure",
    "12-factor app": "DevOps & Infrastructure",
    "Blue-green deployment": "DevOps & Infrastructure",
    "Canary deployment": "DevOps & Infrastructure",
    "Infrastructure as Code": "DevOps & Infrastructure",
    # CI/CD Platforms (from TECHNOLOGIES_LIST)
    "Jenkins": "DevOps & Infrastructure",
    "GitHub Actions": "DevOps & Infrastructure",
    "GitLab CI": "DevOps & Infrastructure",
    "GitLab CI/CD": "DevOps & Infrastructure",
    "CircleCI": "DevOps & Infrastructure",
    "Travis CI": "DevOps & Infrastructure",
    "TeamCity": "DevOps & Infrastructure",
    "Bamboo": "DevOps & Infrastructure",
    "Buildkite": "DevOps & Infrastructure",
    "Drone CI": "DevOps & Infrastructure",
    "Tekton": "DevOps & Infrastructure",
    "Argo Workflows": "DevOps & Infrastructure",
    "FluxCD": "DevOps & Infrastructure",
    "Spinnaker": "DevOps & Infrastructure",
    "Harness": "DevOps & Infrastructure",
    "Octopus Deploy": "DevOps & Infrastructure",
    "Bitbucket Pipelines": "DevOps & Infrastructure",
    "Semaphore CI": "DevOps & Infrastructure",
    "Codefresh": "DevOps & Infrastructure",
    # Containers and Orchestration (from TECHNOLOGIES_LIST)
    "Docker": "DevOps & Infrastructure",
    "Docker Compose": "DevOps & Infrastructure",
    "Docker Swarm": "DevOps & Infrastructure",
    "Podman": "DevOps & Infrastructure",
    "Buildah": "DevOps & Infrastructure",
    "Kubernetes": "DevOps & Infrastructure",
    "K8s": "DevOps & Infrastructure",
    "Helm": "DevOps & Infrastructure",
    "Kustomize": "DevOps & Infrastructure",
    "Skaffold": "DevOps & Infrastructure",
    "OpenShift": "DevOps & Infrastructure",
    "Rancher": "DevOps & Infrastructure",
    "Tanzu": "DevOps & Infrastructure",
    "Nomad": "DevOps & Infrastructure",
    "containerd": "DevOps & Infrastructure",
    "CRI-O": "DevOps & Infrastructure",
    "Knative": "DevOps & Infrastructure",
    "KEDA": "DevOps & Infrastructure",
    "Linkerd": "DevOps & Infrastructure",
    "Istio": "DevOps & Infrastructure",
    "Consul Connect": "DevOps & Infrastructure",
    "OPA": "DevOps & Infrastructure",
    "Gatekeeper": "DevOps & Infrastructure",
    "Falco": "DevOps & Infrastructure",
    # Infrastructure as Code (from TECHNOLOGIES_LIST)
    "Terraform": "DevOps & Infrastructure",
    "OpenTofu": "DevOps & Infrastructure",
    "Pulumi": "DevOps & Infrastructure",
    "AWS CDK": "DevOps & Infrastructure",
    "AWS SAM": "DevOps & Infrastructure",
    "Ansible": "DevOps & Infrastructure",
    "Puppet": "DevOps & Infrastructure",
    "Chef": "DevOps & Infrastructure",
    "SaltStack": "DevOps & Infrastructure",
    "Packer": "DevOps & Infrastructure",
    "Vagrant": "DevOps & Infrastructure",
    "Crossplane": "DevOps & Infrastructure",
    "Terragrunt": "DevOps & Infrastructure",
    "Atlantis": "DevOps & Infrastructure",
    # Monitoring / Logging / Observability (from TECHNOLOGIES_LIST)
    "Prometheus": "DevOps & Infrastructure",
    "Grafana": "DevOps & Infrastructure",
    "Grafana Loki": "DevOps & Infrastructure",
    "Grafana Tempo": "DevOps & Infrastructure",
    "Datadog": "DevOps & Infrastructure",
    "New Relic": "DevOps & Infrastructure",
    "Dynatrace": "DevOps & Infrastructure",
    "AppDynamics": "DevOps & Infrastructure",
    "Splunk": "DevOps & Infrastructure",
    "Sumo Logic": "DevOps & Infrastructure",
    "ELK Stack": "DevOps & Infrastructure",
    "Logstash": "DevOps & Infrastructure",
    "Kibana": "DevOps & Infrastructure",
    "Beats": "DevOps & Infrastructure",
    "Filebeat": "DevOps & Infrastructure",
    "OpenTelemetry": "DevOps & Infrastructure",
    "Jaeger": "DevOps & Infrastructure",
    "Zipkin": "DevOps & Infrastructure",
    "Honeycomb": "DevOps & Infrastructure",
    "Sentry": "DevOps & Infrastructure",
    "Rollbar": "DevOps & Infrastructure",
    "Bugsnag": "DevOps & Infrastructure",
    "PagerDuty": "DevOps & Infrastructure",
    "OpsGenie": "DevOps & Infrastructure",
    "Alertmanager": "DevOps & Infrastructure",
    "Google Cloud Monitoring": "DevOps & Infrastructure",
    "Nagios": "DevOps & Infrastructure",
    "Zabbix": "DevOps & Infrastructure",
    "Netdata": "DevOps & Infrastructure",
    # Service Mesh / API Gateway / Networking (from TECHNOLOGIES_LIST)
    "Consul": "DevOps & Infrastructure",
    "Envoy": "DevOps & Infrastructure",
    "Traefik": "DevOps & Infrastructure",
    "Nginx": "DevOps & Infrastructure",
    "HAProxy": "DevOps & Infrastructure",
    "Caddy": "DevOps & Infrastructure",
    "Kong": "DevOps & Infrastructure",
    "Kong Gateway": "DevOps & Infrastructure",
    "AWS API Gateway": "DevOps & Infrastructure",
    "Apigee": "DevOps & Infrastructure",
    "Cloudflare Workers": "DevOps & Infrastructure",
    "Fastly": "DevOps & Infrastructure",
    # CDN / Edge (from TECHNOLOGIES_LIST)
    "Cloudflare CDN": "DevOps & Infrastructure",
    "Google Cloud CDN": "DevOps & Infrastructure",
    "Vercel Edge": "DevOps & Infrastructure",
    "Netlify Edge Functions": "DevOps & Infrastructure",
    # Storage Services (from TECHNOLOGIES_LIST)
    "Google Cloud Storage": "DevOps & Infrastructure",
    "GCS": "DevOps & Infrastructure",
    "MinIO": "DevOps & Infrastructure",
    "Ceph": "DevOps & Infrastructure",
    "Backblaze B2": "DevOps & Infrastructure",
    # Message Queues / Streaming (from TECHNOLOGIES_LIST)
    "Apache Kafka": "DevOps & Infrastructure",
    "Kafka": "DevOps & Infrastructure",
    "Confluent Kafka": "DevOps & Infrastructure",
    "RabbitMQ": "DevOps & Infrastructure",
    "ActiveMQ": "DevOps & Infrastructure",
    "NATS": "DevOps & Infrastructure",
    "NATS JetStream": "DevOps & Infrastructure",
    "ZeroMQ": "DevOps & Infrastructure",
    "Apache Pulsar": "DevOps & Infrastructure",
    "Pulsar": "DevOps & Infrastructure",
    "Redpanda": "DevOps & Infrastructure",
    "Celery": "DevOps & Infrastructure",
    "Sidekiq": "DevOps & Infrastructure",
    "Bull": "DevOps & Infrastructure",
    "BullMQ": "DevOps & Infrastructure",
    "Temporal": "DevOps & Infrastructure",
    "Apache Camel": "DevOps & Infrastructure",
    # Operating Systems / Infrastructure (from TECHNOLOGIES_LIST)
    "Linux": "DevOps & Infrastructure",
    "Ubuntu": "DevOps & Infrastructure",
    "Debian": "DevOps & Infrastructure",
    "CentOS": "DevOps & Infrastructure",
    "RHEL": "DevOps & Infrastructure",
    "Fedora": "DevOps & Infrastructure",
    "Alpine Linux": "DevOps & Infrastructure",
    "Windows Server": "DevOps & Infrastructure",
    "VMware": "DevOps & Infrastructure",
    "vSphere": "DevOps & Infrastructure",
    "ESXi": "DevOps & Infrastructure",
    "Hyper-V": "DevOps & Infrastructure",
    "KVM": "DevOps & Infrastructure",
    "Proxmox": "DevOps & Infrastructure",
    "Ansible Tower": "DevOps & Infrastructure",
    "AWX": "DevOps & Infrastructure",
    "Tailscale": "DevOps & Infrastructure",
    "WireGuard": "DevOps & Infrastructure",
    "OpenVPN": "DevOps & Infrastructure",
    "Let's Encrypt": "DevOps & Infrastructure",
    "Certbot": "DevOps & Infrastructure",

    # ── Security ──────────────────────────────────────────────────────────────
    "OWASP": "Security",
    "Penetration testing": "Security",
    "Pen testing": "Security",
    "SAST": "Security",
    "DAST": "Security",
    "SCA": "Security",
    "Vulnerability scanning": "Security",
    "Threat modeling": "Security",
    "Zero Trust": "Security",
    "PKI": "Security",
    "Secrets management": "Security",
    "Encryption": "Security",
    "AES": "Security",
    "RSA": "Security",
    "ECC": "Security",
    "SHA": "Security",
    "bcrypt": "Security",
    "RBAC": "Security",
    "ABAC": "Security",
    "GDPR": "Security",
    "HIPAA": "Security",
    "SOC 2": "Security",
    "PCI DSS": "Security",
    "ISO 27001": "Security",
    "FedRAMP": "Security",
    "CVE": "Security",
    "CVSS": "Security",
    "FIDO2": "Security",
    "WebAuthn": "Security",
    "MFA": "Security",
    "2FA": "Security",
    "SIEM": "Security",
    # Security Platforms (from TECHNOLOGIES_LIST)
    "HashiCorp Vault": "Security",
    "Vault": "Security",
    "AWS Secrets Manager": "Security",
    "Google Secret Manager": "Security",
    "Okta": "Security",
    "Auth0": "Security",
    "Keycloak": "Security",
    "FusionAuth": "Security",
    "Ping Identity": "Security",
    "CrowdStrike": "Security",
    "Carbon Black": "Security",
    "SentinelOne": "Security",
    "Snyk": "Security",
    "Aqua Security": "Security",
    "OWASP ZAP": "Security",
    "Burp Suite": "Security",
    "Nessus": "Security",
    "Qualys": "Security",
    "Trivy": "Security",
    "Grype": "Security",
    "AWS Security Hub": "Security",
    "AWS GuardDuty": "Security",

    # ── Testing & Quality ─────────────────────────────────────────────────────
    # Testing (from SKILLS_LIST)
    "pytest": "Testing & Quality",
    "unittest": "Testing & Quality",
    "hypothesis": "Testing & Quality",
    "Jest": "Testing & Quality",
    "Vitest": "Testing & Quality",
    "Mocha": "Testing & Quality",
    "Chai": "Testing & Quality",
    "Jasmine": "Testing & Quality",
    "Karma": "Testing & Quality",
    "Cypress": "Testing & Quality",
    "Playwright": "Testing & Quality",
    "Selenium": "Testing & Quality",
    "WebdriverIO": "Testing & Quality",
    "Puppeteer": "Testing & Quality",
    "Nightwatch.js": "Testing & Quality",
    "Appium": "Testing & Quality",
    "JUnit": "Testing & Quality",
    "TestNG": "Testing & Quality",
    "Mockito": "Testing & Quality",
    "AssertJ": "Testing & Quality",
    "RSpec": "Testing & Quality",
    "Minitest": "Testing & Quality",
    "Capybara": "Testing & Quality",
    "PHPUnit": "Testing & Quality",
    "Pest": "Testing & Quality",
    "Behat": "Testing & Quality",
    "xUnit": "Testing & Quality",
    "NUnit": "Testing & Quality",
    "MSTest": "Testing & Quality",
    "SpecFlow": "Testing & Quality",
    "k6": "Testing & Quality",
    "Locust": "Testing & Quality",
    "JMeter": "Testing & Quality",
    "Gatling": "Testing & Quality",
    "Artillery": "Testing & Quality",
    "Postman": "Testing & Quality",
    "Insomnia": "Testing & Quality",
    "Newman": "Testing & Quality",
    "Pact": "Testing & Quality",
    "WireMock": "Testing & Quality",
    "Cucumber": "Testing & Quality",
    "Behave": "Testing & Quality",
    "SonarQube": "Testing & Quality",
    "SonarCloud": "Testing & Quality",
    "CodeClimate": "Testing & Quality",
    "ESLint": "Testing & Quality",
    "Prettier": "Testing & Quality",
    "Black": "Testing & Quality",
    "Ruff": "Testing & Quality",
    "Flake8": "Testing & Quality",
    "Pylint": "Testing & Quality",
    "Mypy": "Testing & Quality",
    "Rubocop": "Testing & Quality",
    "Stylelint": "Testing & Quality",
    "TDD": "Testing & Quality",
    "BDD": "Testing & Quality",
    "ATDD": "Testing & Quality",
    "mutation testing": "Testing & Quality",
    # Testing / Quality Platforms (from TECHNOLOGIES_LIST)
    "Coverity": "Testing & Quality",
    "Checkmarx": "Testing & Quality",
    "Veracode": "Testing & Quality",
    "Fortify": "Testing & Quality",
    "Browserstack": "Testing & Quality",
    "Sauce Labs": "Testing & Quality",
    "LambdaTest": "Testing & Quality",
    "TestRail": "Testing & Quality",
    "Xray": "Testing & Quality",
    "Zephyr": "Testing & Quality",
    "LaunchDarkly": "Testing & Quality",
    "Split.io": "Testing & Quality",
    "Unleash": "Testing & Quality",

    # ── Developer Tools ───────────────────────────────────────────────────────
    # Build Tools / Bundlers / Package Managers (from SKILLS_LIST)
    "Webpack": "Developer Tools",
    "Vite": "Developer Tools",
    "Rollup": "Developer Tools",
    "Parcel": "Developer Tools",
    "esbuild": "Developer Tools",
    "Turbopack": "Developer Tools",
    "Gulp": "Developer Tools",
    "Grunt": "Developer Tools",
    "Babel": "Developer Tools",
    "SWC": "Developer Tools",
    "npm": "Developer Tools",
    "Yarn": "Developer Tools",
    "pnpm": "Developer Tools",
    "pip": "Developer Tools",
    "Poetry": "Developer Tools",
    "Pipenv": "Developer Tools",
    "uv": "Developer Tools",
    "conda": "Developer Tools",
    "Anaconda": "Developer Tools",
    "Maven": "Developer Tools",
    "Gradle": "Developer Tools",
    "Ant": "Developer Tools",
    "SBT": "Developer Tools",
    "Cargo": "Developer Tools",
    "Bundler": "Developer Tools",
    "RubyGems": "Developer Tools",
    "Composer": "Developer Tools",
    "NuGet": "Developer Tools",
    "MSBuild": "Developer Tools",
    "Bazel": "Developer Tools",
    "Buck": "Developer Tools",
    "Pants": "Developer Tools",
    "Nx": "Developer Tools",
    "Turborepo": "Developer Tools",
    "Lerna": "Developer Tools",
    "Make": "Developer Tools",
    "CMake": "Developer Tools",
    "Meson": "Developer Tools",
    # Version Control (from SKILLS_LIST)
    "Git": "Developer Tools",
    "GitHub": "Developer Tools",
    "GitLab": "Developer Tools",
    "Bitbucket": "Developer Tools",
    "Mercurial": "Developer Tools",
    "SVN": "Developer Tools",
    "Subversion": "Developer Tools",
    "Perforce": "Developer Tools",
    "Git Flow": "Developer Tools",
    "Trunk-based development": "Developer Tools",
    "Feature flags": "Developer Tools",
    "Conventional Commits": "Developer Tools",
    "Semantic versioning": "Developer Tools",
    "SemVer": "Developer Tools",
    # VCS Hosting / Artifact Registries (from TECHNOLOGIES_LIST)
    "Azure Repos": "Developer Tools",
    "Docker Hub": "Developer Tools",
    "JFrog Artifactory": "Developer Tools",
    "Nexus Repository": "Developer Tools",
    "GitHub Packages": "Developer Tools",
    "GitLab Container Registry": "Developer Tools",
    # IDEs and Development Environments (from TECHNOLOGIES_LIST)
    "VS Code": "Developer Tools",
    "Visual Studio Code": "Developer Tools",
    "Visual Studio": "Developer Tools",
    "IntelliJ IDEA": "Developer Tools",
    "IntelliJ": "Developer Tools",
    "PyCharm": "Developer Tools",
    "WebStorm": "Developer Tools",
    "GoLand": "Developer Tools",
    "RubyMine": "Developer Tools",
    "Rider": "Developer Tools",
    "CLion": "Developer Tools",
    "DataGrip": "Developer Tools",
    "PhpStorm": "Developer Tools",
    "Vim": "Developer Tools",
    "Neovim": "Developer Tools",
    "Emacs": "Developer Tools",
    "Eclipse": "Developer Tools",
    "NetBeans": "Developer Tools",
    "Sublime Text": "Developer Tools",
    "Cursor": "Developer Tools",
    "RStudio": "Developer Tools",
    "GitHub Codespaces": "Developer Tools",
    "Gitpod": "Developer Tools",
    "Replit": "Developer Tools",
    # Documentation (from SKILLS_LIST)
    "Markdown": "Developer Tools",
    "Sphinx": "Developer Tools",
    "MkDocs": "Developer Tools",
    "Docusaurus": "Developer Tools",
    "GitBook": "Developer Tools",
    "Confluence": "Developer Tools",
    "JSDoc": "Developer Tools",
    "TSDoc": "Developer Tools",
    "Javadoc": "Developer Tools",
    "Swagger UI": "Developer Tools",
    "Redoc": "Developer Tools",
    # Design Tools (from SKILLS_LIST)
    "Figma": "Developer Tools",
    "Sketch": "Developer Tools",
    "Adobe XD": "Developer Tools",
    "InVision": "Developer Tools",
    "Zeplin": "Developer Tools",
    "Framer": "Developer Tools",
    "Adobe Photoshop": "Developer Tools",
    "Adobe Illustrator": "Developer Tools",

    # ── Specialty ─────────────────────────────────────────────────────────────
    # Game Development (from SKILLS_LIST)
    "Unity": "Specialty",
    "Unreal Engine": "Specialty",
    "Godot": "Specialty",
    "Phaser": "Specialty",
    "Babylon.js": "Specialty",
    "Three.js": "Specialty",
    "WebGL": "Specialty",
    "OpenGL": "Specialty",
    "Vulkan": "Specialty",
    "DirectX": "Specialty",
    # Embedded / Systems (from SKILLS_LIST)
    "Embedded C": "Specialty",
    "RTOS": "Specialty",
    "FreeRTOS": "Specialty",
    "Zephyr": "Specialty",
    "Raspberry Pi": "Specialty",
    "ESP32": "Specialty",
    "STM32": "Specialty",
    "UART": "Specialty",
    "SPI": "Specialty",
    "I2C": "Specialty",
    "CAN bus": "Specialty",
    "Linux kernel": "Specialty",
    "Device drivers": "Specialty",
    "Yocto": "Specialty",
    # Accessibility (from SKILLS_LIST)
    "WCAG": "Specialty",
    "WCAG 2.1": "Specialty",
    "WCAG 2.2": "Specialty",
    "ARIA": "Specialty",
    "WAI-ARIA": "Specialty",
    "Section 508": "Specialty",
    "Accessibility testing": "Specialty",
    "Inclusive design": "Specialty",
    "Universal design": "Specialty",
    # Blockchain / Web3 (from SKILLS_LIST)
    "Blockchain": "Specialty",
    "Ethereum": "Specialty",
    "Web3.js": "Specialty",
    "Ethers.js": "Specialty",
    "Hardhat": "Specialty",
    "Truffle": "Specialty",
    "Foundry": "Specialty",
    "OpenZeppelin": "Specialty",
    "IPFS": "Specialty",
    "Smart contracts": "Specialty",
    # Low-Code / No-Code / Business Platforms (from SKILLS_LIST)
    "Salesforce": "Specialty",
    "Salesforce Lightning": "Specialty",
    "Salesforce Apex": "Specialty",
    "ServiceNow": "Specialty",
    "OutSystems": "Specialty",
    "Mendix": "Specialty",
    "Appian": "Specialty",
    "Retool": "Specialty",
    "WordPress": "Specialty",
    "Shopify": "Specialty",
    "Zapier": "Specialty",
    # Communication / Collaboration tools (from TECHNOLOGIES_LIST)
    "Slack": "Specialty",
    "Microsoft Teams": "Specialty",
    "Discord": "Specialty",
    "Google Chat": "Specialty",
    "Zoom": "Specialty",
    "Webex": "Specialty",
    "Google Meet": "Specialty",
    "Notion": "Specialty",
    "Jira": "Specialty",
    "Linear": "Specialty",
    "Trello": "Specialty",
    "Asana": "Specialty",
    "Monday.com": "Specialty",
    "ClickUp": "Specialty",
    "Basecamp": "Specialty",
    "YouTrack": "Specialty",
    "GitHub Issues": "Specialty",
    "GitLab Issues": "Specialty",
    "Miro": "Specialty",
    "Mural": "Specialty",
    "Lucidchart": "Specialty",

    # ── Leadership & Management ───────────────────────────────────────────────
    # Leadership (from SOFT_SKILLS_LIST)
    "leadership": "Leadership & Management",
    "technical leadership": "Leadership & Management",
    "thought leadership": "Leadership & Management",
    "engineering leadership": "Leadership & Management",
    "team leadership": "Leadership & Management",
    "project leadership": "Leadership & Management",
    "servant leadership": "Leadership & Management",
    "people management": "Leadership & Management",
    "team management": "Leadership & Management",
    "managing distributed teams": "Leadership & Management",
    "managing remote teams": "Leadership & Management",
    "leading cross-functional teams": "Leadership & Management",
    "influence without authority": "Leadership & Management",
    "driving alignment": "Leadership & Management",
    "decision making": "Leadership & Management",
    "decision-making": "Leadership & Management",
    "sound judgment": "Leadership & Management",
    "executive presence": "Leadership & Management",
    "strategic leadership": "Leadership & Management",
    "change leadership": "Leadership & Management",
    "leading through ambiguity": "Leadership & Management",
    "hiring": "Leadership & Management",
    "recruiting": "Leadership & Management",
    "performance management": "Leadership & Management",
    "performance reviews": "Leadership & Management",
    "giving feedback": "Leadership & Management",
    "receiving feedback": "Leadership & Management",
    "constructive feedback": "Leadership & Management",
    "radical candor": "Leadership & Management",
    # Project Management (from SOFT_SKILLS_LIST)
    "project management": "Leadership & Management",
    "program management": "Leadership & Management",
    "portfolio management": "Leadership & Management",
    "delivery management": "Leadership & Management",
    "milestone management": "Leadership & Management",
    "scope management": "Leadership & Management",
    "project planning": "Leadership & Management",
    "workback planning": "Leadership & Management",
    "scheduling": "Leadership & Management",
    "resource management": "Leadership & Management",
    "capacity planning": "Leadership & Management",
    "risk management": "Leadership & Management",
    "risk identification": "Leadership & Management",
    "risk mitigation": "Leadership & Management",
    "dependency management": "Leadership & Management",
    "status reporting": "Leadership & Management",
    "project status updates": "Leadership & Management",
    "budget management": "Leadership & Management",
    "budget tracking": "Leadership & Management",
    "sprint planning": "Leadership & Management",
    "backlog grooming": "Leadership & Management",
    "backlog refinement": "Leadership & Management",
    "release management": "Leadership & Management",
    "release planning": "Leadership & Management",
    "agile project management": "Leadership & Management",
    "scrum master": "Leadership & Management",
    # Strategy and Vision (from SOFT_SKILLS_LIST)
    "strategic thinking": "Leadership & Management",
    "big picture thinking": "Leadership & Management",
    "long-term planning": "Leadership & Management",
    "vision setting": "Leadership & Management",
    "defining vision": "Leadership & Management",
    "technical strategy": "Leadership & Management",
    "engineering strategy": "Leadership & Management",
    "architecture decision-making": "Leadership & Management",
    "technical direction": "Leadership & Management",
    "balancing short-term and long-term": "Leadership & Management",
    "thinking at scale": "Leadership & Management",
    # Influence and Persuasion (from SOFT_SKILLS_LIST)
    "persuasion": "Leadership & Management",
    "persuasive communication": "Leadership & Management",
    "influencing others": "Leadership & Management",
    "consensus building": "Leadership & Management",
    "building consensus": "Leadership & Management",
    "alignment across teams": "Leadership & Management",
    "navigating competing priorities": "Leadership & Management",
    "selling ideas": "Leadership & Management",
    "pitching": "Leadership & Management",
    "advocacy": "Leadership & Management",
    "championing initiatives": "Leadership & Management",

    # ── Interpersonal ─────────────────────────────────────────────────────────
    # Communication (from SOFT_SKILLS_LIST)
    "communication": "Interpersonal",
    "written communication": "Interpersonal",
    "verbal communication": "Interpersonal",
    "technical communication": "Interpersonal",
    "effective communication": "Interpersonal",
    "active listening": "Interpersonal",
    "listening skills": "Interpersonal",
    "presentation skills": "Interpersonal",
    "public speaking": "Interpersonal",
    "storytelling": "Interpersonal",
    "technical writing": "Interpersonal",
    "documentation skills": "Interpersonal",
    "writing skills": "Interpersonal",
    "proposal writing": "Interpersonal",
    "report writing": "Interpersonal",
    "business writing": "Interpersonal",
    "cross-functional communication": "Interpersonal",
    "asynchronous communication": "Interpersonal",
    "meeting facilitation": "Interpersonal",
    "facilitating discussions": "Interpersonal",
    # Team Collaboration (from SOFT_SKILLS_LIST)
    "teamwork": "Interpersonal",
    "collaboration": "Interpersonal",
    "team collaboration": "Interpersonal",
    "cross-functional collaboration": "Interpersonal",
    "cross-team collaboration": "Interpersonal",
    "building relationships": "Interpersonal",
    "relationship building": "Interpersonal",
    "partnership": "Interpersonal",
    "working with stakeholders": "Interpersonal",
    "team player": "Interpersonal",
    "collaborative": "Interpersonal",
    "remote team collaboration": "Interpersonal",
    # Customer / Client Skills (from SOFT_SKILLS_LIST)
    "customer focus": "Interpersonal",
    "customer-centric": "Interpersonal",
    "customer empathy": "Interpersonal",
    "customer service": "Interpersonal",
    "client management": "Interpersonal",
    "client relations": "Interpersonal",
    "client communication": "Interpersonal",
    "stakeholder communication": "Interpersonal",
    "managing expectations": "Interpersonal",
    "expectation setting": "Interpersonal",
    "user empathy": "Interpersonal",
    "user advocacy": "Interpersonal",
    "user research": "Interpersonal",
    "gathering requirements": "Interpersonal",
    "requirements elicitation": "Interpersonal",
    "discovery": "Interpersonal",
    "needs analysis": "Interpersonal",
    "business analysis": "Interpersonal",
    "account management": "Interpersonal",
    "vendor management": "Interpersonal",
    # Teaching / Mentoring (from SOFT_SKILLS_LIST)
    "mentoring": "Interpersonal",
    "mentorship": "Interpersonal",
    "coaching": "Interpersonal",
    "teaching": "Interpersonal",
    "mentoring junior developers": "Interpersonal",
    "guiding junior engineers": "Interpersonal",
    "technical mentorship": "Interpersonal",
    "knowledge sharing": "Interpersonal",
    "knowledge transfer": "Interpersonal",
    "onboarding": "Interpersonal",
    "onboarding new hires": "Interpersonal",
    "pair programming": "Interpersonal",
    "mob programming": "Interpersonal",
    "code review": "Interpersonal",
    "writing documentation": "Interpersonal",
    "creating learning materials": "Interpersonal",
    "workshop facilitation": "Interpersonal",
    "training delivery": "Interpersonal",
    "blogging": "Interpersonal",
    "conference speaking": "Interpersonal",
    # Emotional Intelligence (from SOFT_SKILLS_LIST)
    "emotional intelligence": "Interpersonal",
    "self-awareness": "Interpersonal",
    "empathy": "Interpersonal",
    "empathetic": "Interpersonal",
    "compassion": "Interpersonal",
    "social awareness": "Interpersonal",
    "relationship management": "Interpersonal",
    "conflict resolution": "Interpersonal",
    "conflict management": "Interpersonal",
    "managing difficult conversations": "Interpersonal",
    "psychological safety": "Interpersonal",
    "creating psychological safety": "Interpersonal",
    "patience": "Interpersonal",
    "composure": "Interpersonal",
    "humility": "Interpersonal",
    "intellectual humility": "Interpersonal",
    "open-mindedness": "Interpersonal",
    "open to feedback": "Interpersonal",
    "cultural sensitivity": "Interpersonal",
    "cultural awareness": "Interpersonal",
    # Diversity, Equity, and Inclusion (from SOFT_SKILLS_LIST)
    "diversity and inclusion": "Interpersonal",
    "DEI": "Interpersonal",
    "inclusive leadership": "Interpersonal",
    "equity": "Interpersonal",
    "belonging": "Interpersonal",
    "allyship": "Interpersonal",
    "bias awareness": "Interpersonal",
    "inclusive communication": "Interpersonal",
    "inclusive design": "Interpersonal",
    "accessibility advocacy": "Interpersonal",
    "cross-cultural communication": "Interpersonal",
    "global mindset": "Interpersonal",
    "multicultural teams": "Interpersonal",
    "working across cultures": "Interpersonal",
    # Professional Skills (from SOFT_SKILLS_LIST)
    "fast learner": "Interpersonal",
    "quick learner": "Interpersonal",
    "customer obsession": "Interpersonal",
    "user obsession": "Interpersonal",
    "shipping": "Interpersonal",
    "shipping quickly": "Interpersonal",
    "pragmatism": "Interpersonal",
    "pragmatic": "Interpersonal",
    "quality mindset": "Interpersonal",
    "security mindset": "Interpersonal",
    "documentation culture": "Interpersonal",
    "frugality": "Interpersonal",
    "cost consciousness": "Interpersonal",
    "incident response": "Interpersonal",
    "being on-call": "Interpersonal",
    "postmortem culture": "Interpersonal",
    "learning from failures": "Interpersonal",
    "cross-cultural": "Interpersonal",
    "interpersonal": "Interpersonal",
    "interpersonal skills": "Interpersonal",
    "facilitation": "Interpersonal",
    "coordination": "Interpersonal",

    # ── Problem Solving & Process ─────────────────────────────────────────────
    # Problem Solving / Analytical (from SOFT_SKILLS_LIST)
    "problem solving": "Problem Solving & Process",
    "problem-solving": "Problem Solving & Process",
    "complex problem solving": "Problem Solving & Process",
    "analytical thinking": "Problem Solving & Process",
    "analytical skills": "Problem Solving & Process",
    "critical thinking": "Problem Solving & Process",
    "systems thinking": "Problem Solving & Process",
    "root cause analysis": "Problem Solving & Process",
    "RCA": "Problem Solving & Process",
    "troubleshooting": "Problem Solving & Process",
    "data-driven decision making": "Problem Solving & Process",
    "data-driven": "Problem Solving & Process",
    "structured thinking": "Problem Solving & Process",
    "first principles thinking": "Problem Solving & Process",
    "creative problem solving": "Problem Solving & Process",
    "innovative thinking": "Problem Solving & Process",
    "logical reasoning": "Problem Solving & Process",
    "hypothesis-driven": "Problem Solving & Process",
    "quantitative analysis": "Problem Solving & Process",
    "qualitative analysis": "Problem Solving & Process",
    # Organizational / Planning Skills (from SOFT_SKILLS_LIST)
    "organization": "Problem Solving & Process",
    "organizational skills": "Problem Solving & Process",
    "time management": "Problem Solving & Process",
    "managing time effectively": "Problem Solving & Process",
    "prioritization": "Problem Solving & Process",
    "priority management": "Problem Solving & Process",
    "planning": "Problem Solving & Process",
    "strategic planning": "Problem Solving & Process",
    "operational planning": "Problem Solving & Process",
    "goal setting": "Problem Solving & Process",
    "OKRs": "Problem Solving & Process",
    "execution": "Problem Solving & Process",
    "bias for action": "Problem Solving & Process",
    "multitasking": "Problem Solving & Process",
    "managing multiple priorities": "Problem Solving & Process",
    "attention to detail": "Problem Solving & Process",
    "detail-oriented": "Problem Solving & Process",
    "thoroughness": "Problem Solving & Process",
    "process improvement": "Problem Solving & Process",
    "process documentation": "Problem Solving & Process",
    "workflow optimization": "Problem Solving & Process",
    "deadline management": "Problem Solving & Process",
    "deadline-driven": "Problem Solving & Process",
    "delivering on time": "Problem Solving & Process",
    "follow-through": "Problem Solving & Process",
    "follow-up": "Problem Solving & Process",
    # Agile / Process Skills (from SOFT_SKILLS_LIST)
    "agile": "Problem Solving & Process",
    "agile methodology": "Problem Solving & Process",
    "agile development": "Problem Solving & Process",
    "scrum": "Problem Solving & Process",
    "scrum ceremonies": "Problem Solving & Process",
    "sprint retrospectives": "Problem Solving & Process",
    "kanban": "Problem Solving & Process",
    "lean": "Problem Solving & Process",
    "lean methodology": "Problem Solving & Process",
    "iterative development": "Problem Solving & Process",
    "incremental delivery": "Problem Solving & Process",
    "continuous improvement": "Problem Solving & Process",
    "kaizen": "Problem Solving & Process",
    "retrospectives": "Problem Solving & Process",
    "blameless post-mortems": "Problem Solving & Process",
    "post-mortems": "Problem Solving & Process",
    "standups": "Problem Solving & Process",
    "daily standups": "Problem Solving & Process",
    "estimation": "Problem Solving & Process",
    "story points": "Problem Solving & Process",
    "planning poker": "Problem Solving & Process",
    "velocity tracking": "Problem Solving & Process",
    # Business Skills (from SOFT_SKILLS_LIST)
    "business acumen": "Problem Solving & Process",
    "business understanding": "Problem Solving & Process",
    "understanding business requirements": "Problem Solving & Process",
    "translating business requirements": "Problem Solving & Process",
    "requirements gathering": "Problem Solving & Process",
    "requirements analysis": "Problem Solving & Process",
    "stakeholder management": "Problem Solving & Process",
    "managing stakeholders": "Problem Solving & Process",
    "executive communication": "Problem Solving & Process",
    "C-suite communication": "Problem Solving & Process",
    "product sense": "Problem Solving & Process",
    "product thinking": "Problem Solving & Process",
    "product mindset": "Problem Solving & Process",
    "roadmap planning": "Problem Solving & Process",
    "roadmapping": "Problem Solving & Process",
    "go-to-market": "Problem Solving & Process",
    "launch strategy": "Problem Solving & Process",
    "market awareness": "Problem Solving & Process",
    "competitive analysis": "Problem Solving & Process",
    "cost-benefit analysis": "Problem Solving & Process",
    "trade-off analysis": "Problem Solving & Process",
    "ROI analysis": "Problem Solving & Process",
    "business case development": "Problem Solving & Process",
    "negotiation": "Problem Solving & Process",
    "contract negotiation": "Problem Solving & Process",
    "vendor negotiation": "Problem Solving & Process",
    # Personal Effectiveness (from SOFT_SKILLS_LIST)
    "self-motivated": "Problem Solving & Process",
    "self-starter": "Problem Solving & Process",
    "self-directed": "Problem Solving & Process",
    "proactive": "Problem Solving & Process",
    "initiative": "Problem Solving & Process",
    "taking initiative": "Problem Solving & Process",
    "ownership": "Problem Solving & Process",
    "taking ownership": "Problem Solving & Process",
    "accountability": "Problem Solving & Process",
    "reliability": "Problem Solving & Process",
    "dependability": "Problem Solving & Process",
    "integrity": "Problem Solving & Process",
    "transparency": "Problem Solving & Process",
    "growth mindset": "Problem Solving & Process",
    "continuous learning": "Problem Solving & Process",
    "learning agility": "Problem Solving & Process",
    "intellectual curiosity": "Problem Solving & Process",
    "curiosity": "Problem Solving & Process",
    "desire to learn": "Problem Solving & Process",
    "adaptability": "Problem Solving & Process",
    "adaptable": "Problem Solving & Process",
    "flexibility": "Problem Solving & Process",
    "flexible": "Problem Solving & Process",
    "resilience": "Problem Solving & Process",
    "working under pressure": "Problem Solving & Process",
    "ambiguity tolerance": "Problem Solving & Process",
    "working with ambiguity": "Problem Solving & Process",
    "work ethic": "Problem Solving & Process",
    "hardworking": "Problem Solving & Process",
    "results-oriented": "Problem Solving & Process",
    "results-driven": "Problem Solving & Process",
    "outcome-focused": "Problem Solving & Process",
    "deep work": "Problem Solving & Process",
    "focus": "Problem Solving & Process",
    "autonomy": "Problem Solving & Process",
    "independent worker": "Problem Solving & Process",
    "works independently": "Problem Solving & Process",
    "entrepreneurial": "Problem Solving & Process",
    "entrepreneurial mindset": "Problem Solving & Process",
    "creative": "Problem Solving & Process",
    "creativity": "Problem Solving & Process",
    "innovation": "Problem Solving & Process",
    "innovative": "Problem Solving & Process",
}
